import { LegalPage } from "@/components/LegalPage";

export const metadata = { title: "Políticas de uso | ELYON BARBER ESTUDIO", description: "Políticas de uso del sitio y sistema de reservas de ELYON BARBER ESTUDIO." };

export default function PoliticasDeUsoPage() {
  return <LegalPage title="Políticas de uso" intro="Estas políticas describen las reglas generales para utilizar el sitio web y el sistema de reservas de ELYON BARBER ESTUDIO de forma adecuada, clara y responsable." sections={[
    { title: "Uso del sitio web", paragraphs: ["El sitio está destinado a entregar información sobre los servicios del estudio y facilitar la solicitud de reservas. El usuario debe utilizar sus funciones de manera lícita, responsable y de acuerdo con la finalidad para la que fueron diseñadas."] },
    { title: "Uso del sistema de reservas", paragraphs: ["Para solicitar una reserva, el usuario debe proporcionar información suficiente y correcta, incluyendo nombre, apellido, correo electrónico y teléfono. El usuario es responsable de revisar los datos antes de confirmar la solicitud.", "La disponibilidad mostrada depende de la configuración vigente del estudio y puede cambiar mientras una reserva aún no haya sido confirmada. El sistema aplica controles para evitar que un mismo horario sea reservado simultáneamente."] },
    { title: "Responsabilidades del usuario", bullets: ["Entregar información verdadera, actualizada y que corresponda al propio usuario.", "No utilizar el sistema para realizar reservas falsas, repetitivas, abusivas o con fines distintos de solicitar una atención real.", "No intentar alterar, interferir, sobrecargar o acceder sin autorización a funciones administrativas o técnicas del sitio.", "Revisar la información de la reserva antes de finalizarla y conservar el correo de confirmación cuando corresponda."] },
    { title: "Reservas, cancelaciones y modificaciones", paragraphs: ["Una reserva se considera registrada cuando el sistema confirma su creación. La confirmación enviada por correo contiene los datos principales de la cita.", "Las posibilidades de modificación o cancelación dependen de las funciones disponibles en el sitio y de las reglas de atención vigentes. Si una función específica no está disponible en línea, cualquier gestión adicional deberá realizarse mediante los canales de contacto que el estudio publique en el sitio."] },
    { title: "Disponibilidad y cambios", paragraphs: ["Los horarios, servicios, precios y disponibilidad pueden ser actualizados por la administración del estudio. El sitio mostrará la información que se encuentre configurada y disponible al momento de la consulta o reserva."] },
    { title: "Uso adecuado de la plataforma", paragraphs: ["Está prohibido intentar acceder a áreas restringidas, obtener información de otros usuarios, introducir código malicioso o utilizar automatizaciones que afecten el funcionamiento normal del servicio. El incumplimiento puede provocar el rechazo de solicitudes o la restricción del acceso cuando sea técnicamente posible."] },
    { title: "Limitaciones de responsabilidad", paragraphs: ["Se procura mantener la información del sitio actualizada y el sistema disponible, pero pueden producirse interrupciones, errores técnicos o cambios de disponibilidad por causas ajenas al funcionamiento normal de la plataforma. La información definitiva de una reserva es la que quede registrada correctamente en el sistema y en su confirmación, cuando esta sea enviada."] },
    { title: "Actualizaciones", paragraphs: ["Estas políticas pueden actualizarse para reflejar cambios en el sitio, en el sistema de reservas o en la forma de prestación del servicio. La versión publicada en esta página será la referencia informativa vigente."] },
  ]} />;
}
