import { LegalPage } from "@/components/LegalPage";

export const metadata = { title: "Términos y condiciones | ELYON BARBER ESTUDIO", description: "Términos y condiciones del sitio y sistema de reservas de ELYON BARBER ESTUDIO." };

export default function TerminosYCondicionesPage() {
  return <LegalPage title="Términos y condiciones" intro="Estos términos establecen las condiciones generales de uso del sitio web y del sistema de reservas de ELYON BARBER ESTUDIO, así como las reglas básicas asociadas a la solicitud de servicios." sections={[
    { title: "Condiciones generales", paragraphs: ["El acceso y uso del sitio implica la aceptación de estas condiciones en lo que resulte aplicable. El sitio permite consultar información y solicitar reservas de servicios ofrecidos por ELYON BARBER ESTUDIO."] },
    { title: "Sistema de reservas", paragraphs: ["La reserva requiere completar los datos solicitados y seleccionar un servicio, una fecha y un horario que aparezcan disponibles. El sistema valida la disponibilidad al momento de recibir la solicitud.", "Una vez creada correctamente, la reserva queda registrada con los datos seleccionados y puede visualizarse en el sistema de administración del estudio."] },
    { title: "Confirmación de la reserva", paragraphs: ["Cuando la reserva se registra correctamente, el sistema intenta enviar un correo de confirmación a la dirección indicada por el cliente. La ausencia o retraso de un correo no implica por sí sola que los datos almacenados en el sistema hayan desaparecido; la confirmación debe considerarse junto con el resultado de la reserva mostrado por el sitio."] },
    { title: "Cancelaciones y modificaciones", paragraphs: ["Las reglas de cancelación o modificación pueden depender de las funciones disponibles y de las condiciones operativas del estudio. Cuando el sitio no disponga de una herramienta específica para realizar estos cambios, el cliente deberá utilizar los canales de contacto que se encuentren publicados en el sitio."] },
    { title: "Horarios y asistencia", bullets: ["El cliente debe revisar cuidadosamente la fecha y hora seleccionadas antes de confirmar.", "Se recomienda asistir con la anticipación razonable que permita una atención ordenada.", "La disponibilidad futura puede cambiar cuando el administrador modifique horarios, bloqueos o servicios.", "Una reserva no autoriza a utilizar el sistema para impedir deliberadamente que otros clientes puedan reservar."] },
    { title: "Responsabilidades del cliente", paragraphs: ["El cliente debe proporcionar datos correctos y mantenerlos actualizados cuando corresponda. También debe utilizar el sitio y el sistema de reservas de buena fe, respetando las condiciones aquí descritas y evitando acciones que puedan afectar su funcionamiento o la experiencia de otros usuarios."] },
    { title: "Condiciones de prestación del servicio", paragraphs: ["Los servicios, precios, duraciones y descripciones que se muestran en el sitio corresponden a la configuración vigente del estudio. La administración puede actualizarlos, y el sistema público reflejará la información disponible al momento de la consulta."] },
    { title: "Uso del sitio", paragraphs: ["El usuario no debe intentar acceder a áreas administrativas, manipular información ajena, explotar vulnerabilidades, introducir contenido malicioso ni interferir con la operación normal de la plataforma. El acceso a las funciones administrativas está reservado para personal autorizado."] },
    { title: "Disposiciones generales", paragraphs: ["Estas condiciones pueden actualizarse cuando sea necesario para reflejar cambios en el funcionamiento del sitio, el sistema de reservas o la prestación de servicios. La versión publicada en esta página será la referencia vigente para el uso de la plataforma."] },
  ]} />;
}
