"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useState, type ReactNode } from "react";
import { BrandMark } from "./ui";

const links = [["Dashboard", "/admin"], ["Reservas", "/admin/reservas"], ["Clientes", "/admin/clientes"], ["Servicios", "/admin/servicios"], ["Horarios / Disponibilidad", "/admin/agenda"], ["Configuración", "/admin/configuracion"], ["Versículos", "/admin/versiculos"]] as const;

export function AdminStandaloneSidebar({ children }: { children: ReactNode }) {
  const pathname = usePathname(); const router = useRouter(); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false);
  async function logout() { setBusy(true); try { await fetch("/api/admin/logout", { method: "POST" }); } finally { router.replace("/admin/login"); } }
  const sidebar = <aside className="flex h-full w-[280px] flex-col border-r border-[#dce9e5] bg-white px-4 py-5"><div className="px-2"><BrandMark /></div><div className="mt-8 px-3"><p className="eyebrow text-neutral-400">Centro de control</p><p className="mt-1 text-xs text-neutral-500">Gestión de Elyon Barber</p></div><nav className="mt-4 grid gap-1">{links.map(([label, href], index) => { const active = href === "/admin" ? pathname === href : pathname.startsWith(href); return <Link key={href} href={href} onClick={() => setOpen(false)} className={`group flex items-center gap-3 rounded-lg px-3 py-3 text-sm font-bold transition ${active ? "bg-teal-950 text-white" : "text-neutral-600 hover:bg-[#eef5f3] hover:text-teal-950"}`}><span className={`grid h-8 w-8 place-items-center rounded-lg text-[10px] ${active ? "bg-white/12" : "bg-neutral-100 group-hover:bg-white"}`}>{String(index + 1).padStart(2, "0")}</span>{label}</Link>; })}</nav><div className="mt-auto grid gap-2 pt-6"><Link className="rounded-lg border border-[#dce9e5] bg-[#eef5f3] px-4 py-3 text-center text-sm font-bold text-teal-950 transition hover:border-teal-950" href="/reservar/elyon-barber">Ver sitio público</Link><button onClick={() => void logout()} disabled={busy} className="rounded-lg px-4 py-3 text-left text-sm font-bold text-neutral-500 hover:bg-neutral-50 hover:text-red-700 disabled:opacity-50">{busy ? "Cerrando sesión…" : "Cerrar sesión"}</button></div></aside>;
  return <main className="app-shell min-h-screen text-neutral-950"><div className="fixed inset-y-0 left-0 z-40 hidden lg:block">{sidebar}</div>{open && <div className="fixed inset-0 z-50 bg-neutral-950/40 lg:hidden" onClick={() => setOpen(false)}><div className="h-full w-[min(88vw,320px)]" onClick={(event) => event.stopPropagation()}>{sidebar}</div></div>}<section className="min-h-screen lg:pl-[280px]"><header className="sticky top-0 z-30 border-b border-[#dce9e5] bg-white/90 px-4 py-3 backdrop-blur-xl sm:px-6"><div className="admin-container flex min-h-12 items-center gap-3"><button aria-label="Abrir menú" onClick={() => setOpen(true)} className="rounded-lg border border-[#dce9e5] bg-white px-3 py-2 text-lg lg:hidden">☰</button><div className="min-w-0 flex-1"><p className="hidden text-[10px] font-black uppercase tracking-[0.12em] text-teal-800 sm:block">ELYON BARBER · Administración</p><h1 className="truncate section-title text-[clamp(1.45rem,1.18rem+.8vw,2.15rem)]">{pathname.startsWith("/admin/versiculos") ? "Versículos" : "Servicios"}</h1></div></div></header><div className="admin-container py-4 sm:py-6 xl:py-8">{children}</div></section></main>;
}